Melhoria na tela de noticias
OsivaTech/palpitefc-front-new pull request #30
Opened 2024-07-12 03:11 UTC by adniltonsantos

2024-07-12 13:51 UTC, franciscoasantos requested changes
Incluí algumas alterações de formatação. E incluí um separador entre as noticias. Consegue fazer esses ajustes, por favor ?
![image](https://github.com/user-attachments/assets/e0414d67-41ed-4011-beab-546c670ce676)

2024-07-12 13:51 UTC, franciscoasantos commented on src/components/matchboard-news-tab/index.tsx
> +          <p className="text-white  text-sm max text-justify pt-2 ">
```suggestion
          <p className="text-white text-sm max mb-1 mt-1 font-bold">
```

2024-07-12 13:51 UTC, franciscoasantos commented on src/components/matchboard-news-tab/index.tsx
> +          <p className="text-white  text-lg  text-justify ">{n.title}</p>
```suggestion
          <p className="text-white text-lg leading-none font-bold">{n.title}</p>
```

2024-07-12 13:51 UTC, franciscoasantos commented on src/components/matchboard-news-tab/index.tsx
> +          <p className="text-white  text-sm  text-justify -mt-2 mb-2 ">
```suggestion
          <p className="text-white text-sm leading-none mt-1">
```

2024-07-12 13:51 UTC, franciscoasantos commented on src/components/matchboard-news-tab/index.tsx
```suggestion
import { Separator } from '../ui/separator'

```

2024-07-12 13:51 UTC, franciscoasantos commented on src/components/matchboard-news-tab/index.tsx
> +        </Link>
```suggestion
        <Separator className="my-4 border border-white/20" />
        </Link>
```

2024-07-12 17:09 UTC, adniltonsantos commented
Verificar novamente a tela , se ficou bom ou precisa de algum ajuste fino.

2024-07-13 17:08 UTC, Guilbritto approved these changes

2024-07-13 17:13 UTC, merged